services:
#  php:
#    container_name: tps-php
#    build:
#      dockerfile: ../docker/php/Dockerfile
#    entrypoint: php /var/www/html/artisan octane:frankenphp --max-requests=10
#    entrypoint: php /var/www/html/artisan octane:frankenphp --max-requests=2000 --workers=12
#    ports:
#      - "80:8000"
#      - "443:443"
#    restart: always
#    volumes:
#      - ./:/var/www/html
#    networks:
#      - sail
#    depends_on:
#      - pgsql
#      - redis

  php:
    container_name: tps-php-fpm
    build:
        dockerfile: ../docker/php/fpm/Dockerfile
    volumes:
       - ./:/var/www/html
    depends_on:
      - pgsql
      - redis
  nginx:
    image: nginx:latest
    volumes:
      - ../docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    links:
      - php
    ports:
      - "80:80"
      - "443:443"
  pgsql:
    image: 'postgres:15'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE:-laravel}'
      POSTGRES_USER: '${DB_USERNAME:-user}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - '../shared-files/db:/var/lib/postgresql/data'
#      - './src/vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - '../shared-files/redis:/data'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
networks:
  sail:
    driver: bridge

